### ISSUE TITLE
depend on CleverTap-iOS-SDK 3.9 Can't the latest version 4.1.1 co-exist

### ISSUE THREAD

**Issue by litongde** [CleverTap/clevertap-geofence-ios#3]
Pod::Spec.new do |s|
  s.name                   = 'CleverTapGeofence'
  s.version                = '1.0.1'
  s.summary                = 'CleverTapGeofence provides Geofencing capabilities to CleverTap iOS SDK.'
  s.homepage               = 'https://github.com/CleverTap/clevertap-geofence-ios'
  s.license                = { :type => "MIT" }
  s.author                 = { "CleverTap" => "http://www.clevertap.com" }
  s.source                 = { :git => 'https://github.com/CleverTap/clevertap-geofence-ios.git', :tag => s.version.to_s }
  s.social_media_url       = 'https://twitter.com/CleverTap'

  s.ios.framework          = 'CoreLocation'
  s.ios.deployment_target  = '10.0'
  s.ios.dependency         'CleverTap-iOS-SDK', '~> 3.9'

  s.source_files           = 'Sources/*'
  s.swift_version          = '5.1'
  s.requires_arc           = true
end

**Comment by akashvercetti** [comment]
@litongde Noted. We will update the geofence SDK with the latest iOS SDK refeneces and release asap 👍

**Comment by akashvercetti** [comment]
@litongde  we have released the latest version of Geofence SDK `v1.0.2` which points to the latest CleverTap iOS SDK. 
https://github.com/CleverTap/clevertap-geofence-ios/releases/tag/1.0.2

You will have to slightly modify your Podfile to this:
`pod CleverTap-Geofence-SDK`
